const express = require("express");
const cookie = require("cookie-parser");
const authRoutes = require("./routes/auth.route");
const postRoutes = require("./routes/post.route");
const app = express();
app.use(express.json());
app.use(cookie());
app.use("/api/auth", authRoutes);
app.use("/api/post", postRoutes);
module.exports = app;
